name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git clang clang-format clang-tidy libgtest-dev nlohmann-json3-dev libcli11-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      working-directory: build
      run: cmake ..

    - name: Build
      working-directory: build
      run: cmake --build .

    - name: Run tests
      working-directory: build
      run: ctest --output-on-failure

    - name: Run clang-format check
      run: |
        find . -name '*.cpp' -o -name '*.hpp' | xargs clang-format --dry-run -Werror

    - name: Run clang-tidy check
      working-directory: build
      run: |
        find ../src ../include -name '*.cpp' -o -name '*.hpp' | xargs clang-tidy -p . 